config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dogs.urls', namespace='dogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path

from dogs.apps import DogsConfig
from dogs.views import index, breed

app_name = DogsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('breed/', breed, name='breed'),
    ]

dogs/models.py
from django.db import models

# Create your models here.
class Breed(models.Model):
    title = models.CharField(max_length=50, verbose_name='название')
    overview = models.TextField(verbose_name='описание', blank=True, null=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'порода'
        verbose_name_plural = 'породы'

class Dog(models.Model):
    title = models.CharField(max_length=100, verbose_name='кличка')
    # breed = models.CharField(max_length=100, verbose_name='порода')
    breed = models.ForeignKey(Breed,on_delete=models.CASCADE, verbose_name='порода')
    image = models.ImageField(upload_to='dogs/', null=True, blank=True, verbose_name='фото')
    birthday = models.DateField(verbose_name='дата рождения')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'собака'
        verbose_name_plural = 'собаки'

dogs/views.py
from django.shortcuts import render

from dogs.models import Breed


# Create your views here.
def index(request):
    context = {
        'object_list': Breed.objects.all()[:3],
        'title': 'Питомник - наши породы'
    }
    return render(request, 'dogs/index.html', context)

def breed(request):
    context = {
        'object_list': Breed.objects.all(),
        'title': 'Все наши породы'
    }
    return render(request, 'dogs/breed.html', context)

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }


    </style>


</head>
<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">О нас</h4>
                    <p class="text-muted">Мы – организация, занимающаяся разведением и выращиванием собак одной или
                        нескольких пород и зарегистрированная в РКФ</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Контакты</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'dogs:breed' %}" class="text-white">Породы</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Альбом</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Переключить навигацию">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{title}}</h1>
                <p class="lead text-muted">Что-то краткое и ведущее о коллекции ниже - ее содержание, создатель и т.д.
                    Сделайте ее короткой и интересной, но не слишком короткой, чтобы люди просто не пропустили ее
                    полностью.</p>
                <p>
                    <a href="#" class="btn btn-primary my-2">Главный призыв к действию</a>
                    <a href="#" class="btn btn-secondary my-2">Вторичное действие</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Вернуться наверх</a>
        </p>
        <p class="mb-1">Пример альбома &copy; Bootstrap, но, пожалуйста, скачайте и настройте его под себя!</p>
    </div>
</footer>


<script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>


</body>
</html>

dogs/templates/dogs/breed.html
{% extends 'dogs/base.html' %}

{% block content %}
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 shadow-sm">
        <div class="card-body">
            <p class="card-text">{{ object.title | title }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">к собакам</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}

{% block content %}
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 shadow-sm">
        <div class="card-body">
            <p class="card-text">{{ object.title | title }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">к собакам</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}